[package]
name = "rmob"
version = "1.0.0"
edition = "2021"
description = "Arr! Git mobbing in Rust"

[dependencies]
assert_cmd = "2.0.12"
dirs = "5.0.1"
git2 = "0.18.0"
serde = { version="1.0.188", features = ["derive"] }
serde_json = "1.0.107"
structopt = "0.3.26"
tempfile = "3.8.0"
